Repository nautobot/nautobot, pull requests merged in 2022-04, with the labels that each got.

#1420 IPAM - IPAddress: Change nat_inside to support multiple outside IPs
  nautobot/ipam/api/serializers.py
  nautobot/ipam/api/views.py
  nautobot/ipam/graphql/types.py
  nautobot/ipam/migrations/0006_ipaddress_nat_outside_list.py
  nautobot/ipam/models.py
  nautobot/ipam/templates/ipam/ipaddress.html
  nautobot/ipam/tests/test_api.py
  nautobot/ipam/tests/test_models.py
Labels: type: feature

#1670 Configure drf-spectacular schema to more closely match drf-yasg
  nautobot/core/settings.py
Labels: type: bug

#1666 Fix a few errors in the documentation about imports
  nautobot/docs/installation/migrating-from-netbox.md
  nautobot/docs/models/extras/status.md
Labels: type: documentation

#1219 Adding ARM64 Support
  .github/workflows/ci_integration.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  docker/Dockerfile
  nautobot/docs/docker/index.md
Labels: type: housekeeping

#1659 Add some missing tasks to development/getting-started.md
  nautobot/docs/development/getting-started.md
  tasks.py
Labels: type: documentation
