Repository nautobot/nautobot, pull requests merged in 2022-02, with the labels that each got.

#1376 Fix provision_field overriding custom field
  nautobot/extras/tasks.py
  nautobot/extras/tests/dummy_jobs/test_site_with_custom_field.py
  nautobot/extras/tests/test_jobs.py
Labels: type: bug

#1377 Update Feature Request Template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request_beta.md
Labels: type: housekeeping

#1381 Handle celery_backend_cleanup args/kwargs correctly
  nautobot/core/celery/schedulers.py
Labels: type: bug

#1387 Update Release Schedule Section Pertaining to Patch Releases
  nautobot/docs/development/index.md
Labels: type: documentation

#1363 Implement Dry Run Feature on Create, Update of Git Repository
  nautobot/extras/datasources/__init__.py
  nautobot/extras/datasources/git.py
  nautobot/extras/forms.py
  nautobot/extras/models/datasources.py
  nautobot/extras/templates/extras/gitrepository.html
  nautobot/extras/templates/extras/gitrepository_object_edit.html
  nautobot/extras/tests/test_datasources.py
  nautobot/extras/tests/test_git.py
  nautobot/extras/urls.py
  nautobot/extras/views.py
  nautobot/utilities/git.py
Labels: type: feature
