Repository nautobot/nautobot, pull requests merged in 2022-08, with the labels that each got.

#2142 Fix URL generation for relationships nested API
  nautobot/extras/api/relationships.py
  nautobot/extras/tests/test_api.py
Labels: type: bug

#2029 Update environment variable format to be standard on all
  nautobot/docs/configuration/optional-settings.md
Labels: type: documentation

#2176 Use rich for task output highlighting, print full docker-compose command being run
  poetry.lock
  pyproject.toml
  tasks.py
Labels: type: housekeeping
