Repository nautobot/nautobot, pull requests merged in 2022-07, with the labels that each got.

#1957 Add Plugin Ability to Override Views (Core and Plugin)
  examples/example_plugin/example_plugin/urls.py
  examples/example_plugin/example_plugin/views.py
  examples/example_plugin_with_view_override/example_plugin_with_view_override/__init__.py
  examples/example_plugin_with_view_override/example_plugin_with_view_override/migrations/__init__.py
  examples/example_plugin_with_view_override/example_plugin_with_view_override/views.py
  examples/example_plugin_with_view_override/poetry.lock
  examples/example_plugin_with_view_override/pyproject.toml
  nautobot/core/tests/nautobot_config.py
  nautobot/docs/plugins/development.md
  nautobot/docs/plugins/index.md
  nautobot/docs/release-notes/version-1.4.md
  nautobot/extras/plugins/__init__.py
  nautobot/extras/templates/extras/plugin_detail.html
  nautobot/extras/tests/test_plugins.py
  poetry.lock
  pyproject.toml
Labels: type: feature

#2027 <WIP> Temp solution, made group show up in admin site
  nautobot/core/authentication.py
Labels: type: bug

#2036 Update docs reference of navigation
  nautobot/docs/additional-features/change-logging.md
  nautobot/docs/models/extras/customlink.md
  nautobot/docs/models/extras/exporttemplate.md
Labels: type: documentation

#2035 Update object change context manager to be aware of the change source
  nautobot/core/middleware.py
  nautobot/extras/choices.py
  nautobot/extras/context_managers.py
  nautobot/extras/datasources/registry.py
  nautobot/extras/jobs.py
  nautobot/extras/migrations/0037_objectchange__add_change_context.py
  nautobot/extras/models/change_logging.py
  nautobot/extras/signals.py
  nautobot/extras/templates/extras/objectchange.html
  nautobot/extras/tests/test_changelog.py
  nautobot/extras/tests/test_context_managers.py
  nautobot/extras/tests/test_webhooks.py
Labels: type: feature

#1938 Add Missing Model Fields to Virtualization Filter Sets
  nautobot/dcim/filters.py
  nautobot/dcim/tests/test_filters.py
  nautobot/ipam/querysets.py
  nautobot/utilities/forms/fields.py
  nautobot/utilities/utils.py
  nautobot/virtualization/filters.py
  nautobot/virtualization/tests/test_filters.py
Labels: type: housekeeping

#1785 [MVP] Dynamic Groups of Groups
  development/docker-compose.yml
  nautobot/core/templates/generic/object_detail.html
  nautobot/core/templates/inc/dynamic_groups_panel.html
  nautobot/core/tests/test_views.py
  nautobot/extras/choices.py
  nautobot/extras/filters.py
  nautobot/extras/forms.py
  nautobot/extras/migrations/0038_dynamicgroup__dynamicgroupmembership.py
  nautobot/extras/models/__init__.py
  nautobot/extras/models/groups.py
  nautobot/extras/querysets.py
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/customfield_edit.html
  nautobot/extras/templates/extras/dynamicgroup.html
  nautobot/extras/templates/extras/dynamicgroup_edit.html
  nautobot/extras/templates/extras/secretsgroup_edit.html
  nautobot/extras/tests/integration/test_dynamicgroups.py
  nautobot/extras/tests/test_dynamicgroups.py
  nautobot/extras/tests/test_views.py
  nautobot/extras/views.py
  nautobot/project-static/jquery/jquery.formset.js
  nautobot/project-static/js/forms.js
  nautobot/utilities/filters.py
  nautobot/utilities/forms/fields.py
  nautobot/utilities/templates/utilities/obj_table.html
  nautobot/utilities/tests/test_filters.py
Labels: type: feature

#2083 Test fix
  nautobot/dcim/tests/integration/test_cable_connect_form.py
Labels: type: bug

#1872 Store `job_kwargs` on JobResult Model, Add "Re-run" Button on Job Result List View
  nautobot/core/templates/generic/object_detail.html
  nautobot/docs/models/extras/jobresult.md
  nautobot/docs/release-notes/version-1.4.md
  nautobot/extras/api/serializers.py
  nautobot/extras/api/views.py
  nautobot/extras/jobs.py
  nautobot/extras/migrations/0039_jobresult_job_kwargs.py
  nautobot/extras/models/jobs.py
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/inc/jobresult.html
  nautobot/extras/templates/extras/jobresult.html
  nautobot/extras/tests/test_api.py
  nautobot/extras/views.py
  nautobot/utilities/templates/buttons/add.html
  nautobot/utilities/templates/buttons/clone.html
  nautobot/utilities/templates/buttons/delete.html
  nautobot/utilities/templates/buttons/edit.html
  nautobot/utilities/templates/buttons/import.html
  nautobot/utilities/templatetags/buttons.py
  nautobot/utilities/testing/__init__.py
  nautobot/utilities/testing/api.py
  nautobot/utilities/utils.py
Labels: type: feature

#2025 Cleanup group names, manual approval for flake8
  renovate.json
Labels: type: housekeeping

#2100 Add missing location status migration
  nautobot/dcim/migrations/0014_location_status_data_migration.py
Labels: type: bug
