Repository nautobot/nautobot, pull requests merged in 2022-03, with the labels that each got.

#1299 Add SECURITY.md
  SECURITY.md
Labels: type: housekeeping

#1348 Pin selenium container versions
  .github/workflows/ci.yml
  development/docker-compose.yml
Labels: type: housekeeping

#1359 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: type: housekeeping

#1411 Concrete Job model part 1
  nautobot/core/fields.py
  nautobot/core/signals.py
  nautobot/core/templates/responsive_table.html
  nautobot/core/tests/nautobot_config.py
  nautobot/core/views/generic.py
  nautobot/docs/additional-features/jobs.md
  nautobot/docs/models/extras/gitrepository.md
  nautobot/docs/models/extras/job.md
  nautobot/docs/release-notes/version-1.3.md
  nautobot/docs/user-guides/git-data-source.md
  nautobot/docs/user-guides/images/git-as-data-source/01-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/02-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/03-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/04-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/06-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/10-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/12-git-data-source.png
  nautobot/docs/user-guides/images/git-as-data-source/13-git-data-source.png
  nautobot/extras/api/serializers.py
  nautobot/extras/api/views.py
  nautobot/extras/apps.py
  nautobot/extras/choices.py
  nautobot/extras/constants.py
  nautobot/extras/datasources/git.py
  nautobot/extras/filters.py
  nautobot/extras/forms.py
  nautobot/extras/jobs.py
  nautobot/extras/migrations/0023_job_model.py
  nautobot/extras/migrations/0024_job_data_migration.py
  nautobot/extras/models/jobs.py
  nautobot/extras/plugins/__init__.py
  nautobot/extras/signals.py
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/inc/job_table.html
  nautobot/extras/templates/extras/inc/overridable_field.html
  nautobot/extras/templates/extras/job_detail.html
  nautobot/extras/templates/extras/job_edit.html
  nautobot/extras/templates/extras/job_list.html
  nautobot/extras/tests/example_jobs/api_test_job.py
  nautobot/extras/tests/example_jobs/test_file_upload_fail.py
  nautobot/extras/tests/example_jobs/test_file_upload_pass.py
  nautobot/extras/tests/test_api.py
  nautobot/extras/tests/test_filters.py
  nautobot/extras/tests/test_jobs.py
  nautobot/extras/tests/test_models.py
  nautobot/extras/tests/test_scripts.py
  nautobot/extras/tests/test_views.py
  nautobot/extras/urls.py
  nautobot/extras/utils.py
  nautobot/extras/views.py
Labels: type: feature

#1434 Add Ability to Filter Objects Missing Custom Field Values via `null`
  nautobot/extras/filters.py
  nautobot/extras/tests/test_customfields.py
Labels: type: feature

#1423 Update Window History State Handling for View with Tabs
  nautobot/core/templates/generic/object_detail.html
  nautobot/dcim/templates/dcim/device/base.html
Labels: type: bug

#1419 Add Documentation for Specifying CA Cert File for LDAP Auth Backend
  nautobot/docs/configuration/authentication/ldap.md
Labels: type: documentation, question

#1366 Circuit termination detail view
  nautobot/circuits/forms.py
  nautobot/circuits/migrations/0007_circuitterminations_primary_model.py
  nautobot/circuits/models.py
  nautobot/circuits/templates/circuits/circuittermination.html
  nautobot/circuits/templates/circuits/circuittermination_edit.html
  nautobot/circuits/templates/circuits/inc/circuit_termination.html
  nautobot/circuits/urls.py
  nautobot/circuits/views.py
  nautobot/core/templates/generic/object_detail.html
  nautobot/extras/templates/extras/inc/tags_panel.html
Labels: type: feature

#1446 Injecting labels into Docker image
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: type: housekeeping

#1444 Adding more docker tags
  .github/workflows/release.yml
  nautobot/docs/docker/index.md
Labels: type: housekeeping

#1439 Cleanup and streamline our integration test bases
  nautobot/circuits/tests/integration/test_relationships.py
  nautobot/core/tests/integration/test_home.py
  nautobot/core/tests/integration/test_navbar.py
  nautobot/core/tests/integration/test_plugin_home.py
  nautobot/core/tests/integration/test_plugin_navbar.py
  nautobot/core/tests/test_graphql.py
  nautobot/docs/development/getting-started.md
  nautobot/extras/tests/integration/test_computedfields.py
  nautobot/extras/tests/integration/test_configcontextschema.py
  nautobot/extras/tests/integration/test_customfields.py
  nautobot/extras/tests/integration/test_plugin_banner.py
  nautobot/extras/tests/integration/test_plugins.py
  nautobot/extras/tests/integration/test_relationships.py
  nautobot/extras/tests/test_customfields.py
  nautobot/extras/tests/test_models.py
  nautobot/ipam/tests/integration/test_prefixes.py
  nautobot/utilities/testing/integration.py
Labels: type: housekeeping

#1425 Dynamic Groups feature (phase 1)
  nautobot/core/api/pagination.py
  nautobot/core/models/generics.py
  nautobot/core/templates/generic/object_detail.html
  nautobot/core/templates/inc/dynamic_groups_panel.html
  nautobot/dcim/filters.py
  nautobot/dcim/models/devices.py
  nautobot/dcim/templates/dcim/device.html
  nautobot/dcim/tests/test_filters.py
  nautobot/docs/release-notes/version-1.3.md
  nautobot/extras/api/nested_serializers.py
  nautobot/extras/api/serializers.py
  nautobot/extras/api/urls.py
  nautobot/extras/api/views.py
  nautobot/extras/constants.py
  nautobot/extras/filters.py
  nautobot/extras/forms.py
  nautobot/extras/groups.py
  nautobot/extras/migrations/0029_dynamicgroup.py
  nautobot/extras/models/__init__.py
  nautobot/extras/models/groups.py
  nautobot/extras/models/mixins.py
  nautobot/extras/models/relationships.py
  nautobot/extras/navigation.py
  nautobot/extras/querysets.py
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/dynamicgroup.html
  nautobot/extras/templates/extras/dynamicgroup_edit.html
  nautobot/extras/tests/test_api.py
  nautobot/extras/tests/test_dynamicgroups.py
  nautobot/extras/tests/test_views.py
  nautobot/extras/urls.py
  nautobot/extras/views.py
  nautobot/ipam/forms.py
  nautobot/utilities/filters.py
  nautobot/utilities/forms/fields.py
  nautobot/utilities/templatetags/helpers.py
  nautobot/utilities/tests/test_utils.py
  nautobot/utilities/utils.py
  nautobot/virtualization/models.py
Labels: type: feature

#1488 Require Pillow 9.0.1 or later for Python >= 3.7 in develop
  nautobot/docs/release-notes/version-1.2.md
  poetry.lock
  pyproject.toml
Labels: group: security

#1075 JSON type for Custom Fields
  nautobot/core/templates/inc/custom_fields/panel_data.html
  nautobot/extras/choices.py
  nautobot/extras/forms.py
  nautobot/extras/models/customfields.py
  nautobot/extras/tests/integration/test_customfields.py
  nautobot/extras/tests/test_customfields.py
Labels: type: feature

#1502 Dynamic Groups Feature (phase 2)
  examples/example_plugin/example_plugin/migrations/0004_example_plugin_dynamicgroup.py
  examples/example_plugin/example_plugin/models.py
  mkdocs.yml
  nautobot/core/models/generics.py
  nautobot/core/settings.py
  nautobot/docs/additional-features/dynamic-groups.md
  nautobot/docs/models/extras/dynamicgroup.md
  nautobot/extras/api/views.py
  nautobot/extras/groups.py
  nautobot/extras/models/groups.py
  nautobot/extras/querysets.py
  nautobot/extras/tests/integration/test_dynamicgroups.py
  nautobot/extras/tests/test_dynamicgroups.py
  nautobot/extras/views.py
Labels: type: feature
