Repository nautobot/nautobot, pull requests merged in 2023-05, with the labels that each got.

#3669 Add Time, Status Indexes to JobResult
  changes/3669.added
  nautobot/extras/migrations/0058_jobresult_add_time_status_idxs.py
  nautobot/extras/models/jobs.py
Labels: type: housekeeping

#3704 Fix `related_name` performance for Git Repo Jobs
  changes/3704.fixed
  nautobot/extras/models/jobs.py
Labels: type: bug

#2549 [WIP] Constance Config for SSO, Multiple SSO Support
  development/dev.env
  nautobot/core/settings.py
  nautobot/core/settings_funcs.py
  nautobot/core/sso.py
  nautobot/core/templates/login.html
  nautobot/utilities/templatetags/helpers.py
Labels: hold pr

#2621 [WIP] Redundancy Interface Group
  changes/1892.added
  changes/1892.changed
  changes/2615.changed
  changes/2615.fixed
  nautobot/core/management/commands/generate_test_data.py
  nautobot/dcim/api/nested_serializers.py
  nautobot/dcim/api/serializers.py
  nautobot/dcim/api/urls.py
  nautobot/dcim/api/views.py
  nautobot/dcim/choices.py
  nautobot/dcim/factory.py
  nautobot/dcim/filters.py
  nautobot/dcim/forms.py
  nautobot/dcim/homepage.py
  nautobot/dcim/migrations/0018_device_redundancy_group.py
  nautobot/dcim/migrations/0019_device_redundancy_group_data_migration.py
  nautobot/dcim/migrations/0020_interface_redundancy_group.py
  nautobot/dcim/models/__init__.py
  nautobot/dcim/models/devices.py
  nautobot/dcim/navigation.py
  nautobot/dcim/tables/__init__.py
  nautobot/dcim/tables/devices.py
  nautobot/dcim/templates/dcim/device.html
  nautobot/dcim/templates/dcim/device_edit.html
  nautobot/dcim/templates/dcim/deviceredundancygroup_create.html
  nautobot/dcim/templates/dcim/deviceredundancygroup_retrieve.html
  nautobot/dcim/tests/test_api.py
  nautobot/dcim/tests/test_filters.py
  nautobot/dcim/tests/test_forms.py
  nautobot/dcim/tests/test_models.py
  nautobot/dcim/tests/test_views.py
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
  nautobot/extras/filters.py
  nautobot/extras/forms/forms.py
  nautobot/extras/management/__init__.py
  nautobot/extras/migrations/0052_configcontext_device_redundancy_groups.py
  nautobot/extras/models/models.py
  nautobot/extras/querysets.py
  nautobot/extras/templates/extras/configcontext.html
  nautobot/extras/templates/extras/configcontext_edit.html
  nautobot/ipam/factory.py
  nautobot/ipam/querysets.py
  nautobot/ipam/tests/test_api.py
  nautobot/ipam/tests/test_models.py
  nautobot/ipam/tests/test_querysets.py
  nautobot/ipam/tests/test_views.py
  nautobot/tenancy/tests/test_views.py
  nautobot/utilities/testing/views.py
  nautobot/utilities/tests/test_filters.py
  nautobot/virtualization/tests/test_filters.py
Labels: hold pr

#2657 [WIP] Introduce RestrictedQuerySet.with_related.
  changes/2657.added
  nautobot/utilities/querysets.py
  nautobot/utilities/tests/test_querysets.py
Labels: hold pr
