Repository nautobot/nautobot, pull requests merged in 2023-07, with the labels that each got.

#4049 Update mkdocstrings and mkdocstrings-python, pin griffe, restructure poetry dependencies
  changes/4049.changed
  changes/4049.dependencies
  nautobot/docs/requirements.txt
  poetry.lock
  pyproject.toml
Labels: type: documentation, dependencies

#4071 Fix Pre-release Tag Format in GitHub Action
  .github/workflows/prerelease.yml
  changes/4071.fixed
Labels: type: housekeeping

#4077 Added ability for Nautobot to send installation metrics.
  changes/4047.added
  development/dev.env
  nautobot/core/cli.py
  nautobot/core/management/commands/post_upgrade.py
  nautobot/core/management/commands/send_installation_metrics.py
  nautobot/core/runner/runner.py
  nautobot/core/runner/settings.py
  nautobot/core/settings.py
  nautobot/core/templates/nautobot_config.py.j2
  nautobot/docs/administration/nautobot-server.md
  nautobot/docs/configuration/optional-settings.md
  nautobot/docs/release-notes/version-1.6.md
Labels: impact: high
