Repository nautobot/nautobot, pull requests merged in 2023-08, with the labels that each got.

#4178 Fix DynamicGroup Serialization Bug
  changes/4178.fixed
  examples/example_plugin/example_plugin/filter_extensions.py
  nautobot/extras/models/groups.py
  nautobot/extras/tests/test_dynamicgroups.py
  nautobot/utilities/forms/fields.py
Labels: type: bug

#4112 Run unittests in parallel
  .github/workflows/ci_pullrequest.yml
  .gitignore
  changes/4112.added
  changes/4112.fixed
  development/dev.env
  development/docker-compose.yml
  nautobot/core/api/views.py
  nautobot/core/tests/nautobot_config.py
  nautobot/core/tests/runner.py
  nautobot/core/tests/tests-times.json
  poetry.lock
  pyproject.toml
  tasks.py
Labels: type: housekeeping

#4150 Platform.network_driver field and associated functionality
  changes/4136.added
  nautobot/core/graphql/schema.py
  nautobot/core/settings.py
  nautobot/dcim/api/serializers.py
  nautobot/dcim/constants.py
  nautobot/dcim/factory.py
  nautobot/dcim/filters/__init__.py
  nautobot/dcim/forms.py
  nautobot/dcim/graphql/types.py
  nautobot/dcim/migrations/0021_platform_network_driver.py
  nautobot/dcim/models/devices.py
  nautobot/dcim/tables/devices.py
  nautobot/dcim/templates/dcim/platform.html
  nautobot/dcim/templates/dcim/platform_edit.html
  nautobot/dcim/tests/test_api.py
  nautobot/dcim/tests/test_filters.py
  nautobot/dcim/tests/test_graphql.py
  nautobot/dcim/tests/test_models.py
  nautobot/dcim/tests/test_views.py
  nautobot/dcim/utils.py
  nautobot/dcim/views.py
  nautobot/docs/configuration/optional-settings.md
  nautobot/docs/models/dcim/platform.md
  nautobot/docs/release-notes/version-1.6.md
  nautobot/docs/user-guides/getting-started/platforms.md
  nautobot/docs/user-guides/images/getting-started-nautobot-ui/10-add-platform.png
  nautobot/extras/tests/constants.py
  nautobot/extras/tests/test_api.py
  nautobot/extras/tests/test_filters.py
  nautobot/extras/tests/test_views.py
  poetry.lock
  pyproject.toml
Labels: impact: high

#4177 Interface redundancy groups
  changes/2825.added
  nautobot/core/api/schema.py
  nautobot/core/settings.py
  nautobot/dcim/api/nested_serializers.py
  nautobot/dcim/api/serializers.py
  nautobot/dcim/api/urls.py
  nautobot/dcim/api/views.py
  nautobot/dcim/choices.py
  nautobot/dcim/filters/__init__.py
  nautobot/dcim/forms.py
  nautobot/dcim/homepage.py
  nautobot/dcim/migrations/0022_interface_redundancy_group.py
  nautobot/dcim/migrations/0023_interface_redundancy_group_data_migration.py
  nautobot/dcim/models/__init__.py
  nautobot/dcim/models/device_components.py
  nautobot/dcim/navigation.py
  nautobot/dcim/tables/__init__.py
  nautobot/dcim/tables/devices.py
  nautobot/dcim/tables/template_code.py
  nautobot/dcim/templates/dcim/interface.html
  nautobot/dcim/templates/dcim/interfaceredundancygroup_retrieve.html
  nautobot/dcim/templates/dcim/interfaceredundancygroupassociation_create.html
  nautobot/dcim/tests/test_api.py
  nautobot/dcim/tests/test_filters.py
  nautobot/dcim/tests/test_models.py
  nautobot/dcim/tests/test_views.py
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
  nautobot/extras/management/__init__.py
  nautobot/ipam/tests/test_models.py
Labels: impact: high

#4092 Add Dynamic Group membership caching.
  changes/3269.added
  nautobot/core/management/commands/post_upgrade.py
  nautobot/core/management/commands/refresh_content_type_cache.py
  nautobot/core/models/__init__.py
  nautobot/core/settings.py
  nautobot/core/templates/inc/dynamic_groups_panel.html
  nautobot/core/templates/nautobot_config.py.j2
  nautobot/core/tests/nautobot_config.py
  nautobot/core/tests/test_models.py
  nautobot/dcim/graphql/types.py
  nautobot/docs/administration/nautobot-server.md
  nautobot/docs/configuration/optional-settings.md
  nautobot/docs/models/extras/dynamicgroup.md
  nautobot/extras/management/commands/refresh_dynamic_group_member_caches.py
  nautobot/extras/models/groups.py
  nautobot/extras/models/mixins.py
  nautobot/extras/querysets.py
  nautobot/extras/signals.py
  nautobot/extras/tests/test_dynamicgroups.py
  nautobot/extras/views.py
  nautobot/ipam/graphql/types.py
  nautobot/virtualization/graphql/types.py
Labels: type: feature, impact: high

#4214 Eject react and fix build bug
  changes/4083.fixed
  nautobot/ui/config/env.js
  nautobot/ui/config/getHttpsConfig.js
  nautobot/ui/config/jest/babelTransform.js
  nautobot/ui/config/jest/cssTransform.js
  nautobot/ui/config/jest/fileTransform.js
  nautobot/ui/config/modules.js
  nautobot/ui/config/paths.js
  nautobot/ui/config/webpack.config.js
  nautobot/ui/config/webpack/persistentCache/createEnvironmentHash.js
  nautobot/ui/config/webpackDevServer.config.js
  nautobot/ui/craco.config.js
  nautobot/ui/jest.config.js
  nautobot/ui/jsconfig.json
  nautobot/ui/lib/nautobot-craco-alias-plugin.js
  nautobot/ui/package-lock.json
  nautobot/ui/package.json
  nautobot/ui/scripts/build.js
  nautobot/ui/scripts/start.js
  nautobot/ui/scripts/test.js
  tasks.py
Labels: emergent

#4291 Fixed warning message when trying to use bulk edit with no items selected.
  changes/4262.fixed
  nautobot/core/views/mixins.py
Labels: triage

#4302 Fixed a permissions issue when using `final-dev` containers
  changes/4300.fixed
  docker/Dockerfile
Labels: emergent

#4319 Release v2.0.0rc2
  changes/2807.changed
  changes/2807.fixed
  changes/2807.removed
  changes/2853.changed
  changes/2853.removed
  changes/3794.added
  changes/4299.fixed
  changes/4300.fixed
  changes/4305.changed
  nautobot/docs/release-notes/version-2.0.md
  nautobot/ui/package-lock.json
  nautobot/ui/package.json
  poetry.lock
  pyproject.toml
Labels: emergent
