Repository nautobot/nautobot, pull requests merged in 2024-09, with the labels that each got.

#6175 Avoid exceptions when encountering a model that doesn't inherit from BaseModel
  changes/6175.fixed
  nautobot/core/tables.py
  nautobot/core/templatetags/buttons.py
  nautobot/core/views/utils.py
  nautobot/extras/forms/mixins.py
Labels: emergent

#6215 Disable coverage during test database setup
  changes/5376.housekeeping
  nautobot/core/tests/runner.py
  tasks.py
Labels: emergent

#6230 Updating datetime.timedelta
  changes/6230.fixed
  nautobot/core/celery/schedulers.py
Labels: type: bug, ms

#6213 Changed `--cache-test-fixtures` and `--keepdb` flags from opt-in to opt-out for `inv unittest` and `inv integration-test` commands.
  .github/workflows/ci_integration.yml
  .github/workflows/ci_pullrequest.yml
  changes/5859.housekeeping
  nautobot/dcim/tests/test_filters.py
  nautobot/docs/development/core/getting-started.md
  tasks.py
Labels: emergent

#6248 Fixed Device Type link and count from Device Family Detail View.
  changes/6248.fixed
  nautobot/dcim/templates/dcim/devicefamily_retrieve.html
  nautobot/dcim/views.py
Labels: type: bug

#6216 Refactored SavedViewUIViewSet to take into account of `permissions_class` attribute.
  changes/5802.housekeeping
  examples/example_app/example_app/urls.py
  examples/example_app/example_app/views.py
  nautobot/core/tests/test_views.py
  nautobot/core/views/mixins.py
  nautobot/extras/views.py
Labels: emergent

#6285 Add --no-reusedb option to unittest
  changes/6285.housekeeping
  nautobot/core/tests/runner.py
  nautobot/docs/development/core/getting-started.md
  tasks.py
Labels: emergent
