Repository nautobot/nautobot, pull requests merged in 2024-01, with the labels that each got.

#5035 fix failing docker builds
  changes/5035.removed
  docker/Dockerfile
Labels: emergent

#5054 Improve IPAddressEditView and IPAddressAssignView logic
  changes/5054.fixed
  changes/5054.security
  nautobot/core/views/mixins.py
  nautobot/ipam/utils/__init__.py
  nautobot/ipam/views.py
Labels: type: bug, emergent

#5095 Job-related bug fixes
  changes/5095.fixed
  nautobot/extras/datasources/git.py
  nautobot/extras/tables.py
Labels: emergent

#5087 update gitpython to 3.1.41 (ltm)
  changes/5087.dependencies
  examples/example_plugin/docs/requirements.txt
  nautobot/docs/requirements.txt
  poetry.lock
  pyproject.toml
Labels: dependencies, emergent

#5086 [Snyk] Security upgrade jinja2 from 3.1.2 to 3.1.3
  changes/5086.dependencies
  examples/example_plugin/docs/requirements.txt
  nautobot/docs/requirements.txt
  poetry.lock
  pyproject.toml
Labels: dependencies, emergent

#5109 Remove `files/get` endpoint which is not used
  changes/5109.security
  nautobot/core/tests/test_views.py
  nautobot/core/urls.py
Labels: emergent

#5102 More job fixes
  changes/5102.added
  changes/5102.changed
  changes/5102.fixed
  nautobot/core/celery/backends.py
  nautobot/core/tests/test_logging.py
  nautobot/core/utils/logging.py
  nautobot/extras/jobs.py
  nautobot/extras/management/commands/runjob.py
  nautobot/extras/models/jobs.py
  nautobot/extras/tests/test_jobs.py
Labels: emergent

#5081 BugFix cf table entry rendering
  changes/5081.fixed
  nautobot/core/tables.py
Labels: emergent

#5131 Add `TreeManager.max_depth` cachedproperty as an alternative to `max_tree_depth()`
  changes/5131.changed
  nautobot/core/models/tree_queries.py
  nautobot/core/signals.py
  nautobot/core/tests/test_models.py
  nautobot/dcim/models/locations.py
  nautobot/dcim/tests/test_models.py
  nautobot/docs/development/core/natural-keys.md
  nautobot/extras/querysets.py
Labels: emergent

#5130 Add experimental `--parallel` option to `invoke unittest`
  changes/5130.housekeeping
  nautobot/core/management/commands/generate_test_data.py
  nautobot/core/tests/runner.py
  nautobot/core/tests/test_graphql.py
  nautobot/ipam/factory.py
  poetry.lock
  pyproject.toml
  tasks.py
Labels: emergent

#5154 [LTM] Bump pillow to 10.2.0 for security fixes
  changes/5151.security
  poetry.lock
  pyproject.toml
Labels: dependencies

#5146 Update sidebar navigation menu styling and behavior
  changes/5146.fixed
  nautobot/core/templates/inc/nav_menu.html
  nautobot/project-static/css/base.css
  nautobot/project-static/css/dark.css
Labels: type: enhancement
