Repository nautobot/nautobot, pull requests merged in 2024-04, with the labels that each got.

#5429 Add Python 3.12 support
  .github/workflows/build_dependency_image.yml
  .github/workflows/build_dependency_image_conditional.yml
  .github/workflows/ci_integration.yml
  .github/workflows/ci_pullrequest.yml
  .github/workflows/plugin_upstream_testing_base.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  changes/5429.added
  changes/5429.changed
  changes/5429.dependencies
  changes/5429.housekeeping
  docker/Dockerfile
  examples/example_app/pyproject.toml
  nautobot/docs/development/core/release-checklist.md
  nautobot/docs/index.md
  nautobot/docs/user-guide/administration/installation/docker.md
  nautobot/docs/user-guide/administration/installation/index.md
  poetry.lock
  pyproject.toml
  tasks.py
Labels: emergent

#5521 Update minor versions of *many* dependencies.
  .github/workflows/ci_integration.yml
  .github/workflows/ci_pullrequest.yml
  changes/5521.dependencies
  changes/5521.security
  development/docker-compose.yml
  development/nautobot_config.py
  examples/azure_ad/group_sync.py
  examples/example_app/example_app/signals.py
  examples/okta/group_sync.py
  examples/s3_static_files/README.md
  nautobot/core/forms/widgets.py
  nautobot/core/graphql/schema.py
  nautobot/core/signals.py
  nautobot/core/templates/nautobot_config.py.j2
  nautobot/core/tests/integration/test_view_authentication.py
  nautobot/core/utils/data.py
  nautobot/dcim/tests/test_signals.py
  nautobot/docs/requirements.txt
  nautobot/docs/user-guide/administration/guides/s3-django-storage.md
  nautobot/extras/health_checks.py
  nautobot/extras/jobs.py
  nautobot/extras/managers.py
  nautobot/extras/models/datasources.py
  nautobot/extras/models/mixins.py
  nautobot/extras/querysets.py
  nautobot/extras/secrets/providers.py
  poetry.lock
  pyproject.toml
Labels: emergent

#5548 Fix TransactionTestCase MRO
  changes/5547.housekeeping
  nautobot/core/testing/__init__.py
Labels: emergent

#5442 System Job for cleaning up ObjectChange records
  changes/2352.fixed
  changes/3749.added
  changes/3749.changed
  changes/3749.removed
  changes/5442.added
  changes/5442.fixed
  nautobot/core/jobs/__init__.py
  nautobot/core/jobs/cleanup.py
  nautobot/core/management/commands/generate_test_data.py
  nautobot/core/settings.yaml
  nautobot/core/templates/generic/object_changelog.html
  nautobot/core/testing/api.py
  nautobot/core/testing/views.py
  nautobot/core/tests/test_authentication.py
  nautobot/core/tests/test_filters.py
  nautobot/core/tests/test_jobs.py
  nautobot/dcim/tests/test_views.py
  nautobot/docs/release-notes/version-2.3.md
  nautobot/extras/factory.py
  nautobot/extras/signals.py
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/objectchange_list.html
  nautobot/extras/tests/test_api.py
  nautobot/extras/tests/test_changelog.py
  nautobot/extras/tests/test_context_managers.py
  nautobot/extras/tests/test_filters.py
  nautobot/extras/tests/test_models.py
  nautobot/extras/tests/test_webhooks.py
  nautobot/ipam/factory.py
  nautobot/ipam/tests/test_api.py
  nautobot/tenancy/factory.py
Labels: emergent

#5604 Add Device Redundancy Groups to Config Contexts
  changes/5603.fixed
  nautobot/extras/datasources/git.py
Labels: type: bug

#5618 [2.2] View for associating locations to contacts and bulk creation
  changes/5034.added
  nautobot/dcim/choices.py
  nautobot/dcim/forms.py
  nautobot/dcim/templates/dcim/location.html
  nautobot/dcim/templates/dcim/location_migrate_data_to_contact.html
  nautobot/dcim/tests/test_views.py
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
  nautobot/extras/views.py
Labels: emergent

#5626 Add extras features docs to new model checklist
  changes/5626.documentation
  nautobot/docs/development/core/model-checklist.md
  nautobot/docs/development/core/model-features.md
  nautobot/extras/constants.py
Labels: type: documentation, emergent

#5627 [LTM] increases performance of `/api/dcim/devices?brief=true` endpoint
  changes/5626.fixed
  nautobot/core/api/views.py
Labels: status: waiting for feedback
