Repository nautobot/nautobot, pull requests merged in 2024-02, with the labels that each got.

#5248 Development dependency updates for next
  .github/workflows/ci_integration.yml
  .github/workflows/ci_pullrequest.yml
  changes/5248.dependencies
  changes/5248.documentation
  changes/5248.housekeeping
  development/docker-compose.yml
  examples/example_app/docs/requirements.txt
  examples/example_app/mkdocs.yml
  mkdocs.yml
  nautobot/core/models/tree_queries.py
  nautobot/core/testing/integration.py
  nautobot/core/tests/test_filters.py
  nautobot/docs/requirements.txt
  poetry.lock
  pyproject.toml
  tasks.py
Labels: dependencies

#5329 Add caching of ChangeLoggedModelsQuery().as_queryset() for enqueue_job_hooks()
  changes/5329.added
  nautobot/extras/jobs.py
  nautobot/extras/tests/test_jobs.py
  nautobot/extras/utils.py
Labels: emergent

#5172 Add collapsible navbar functionality
  changes/5172.added
  changes/5172.fixed
  nautobot/circuits/tests/integration/test_relationships.py
  nautobot/core/templates/base_django.html
  nautobot/core/templates/inc/footer.html
  nautobot/core/templates/inc/nav_menu.html
  nautobot/core/templates/search_form.html
  nautobot/core/tests/test_views.py
  nautobot/project-static/css/base.css
Labels: type: enhancement

#4512 Resolved KeyError on custom actions
  changes/4511.documentation
  nautobot/docs/development/apps/api/views/nautobotuiviewset.md
Labels: status: waiting for feedback

#5342 Switch from curl-based default Docker healthcheck to a CLI-based one
  changes/5342.added
  changes/5342.changed
  development/docker-compose.final.yml
  development/docker-compose.yml
  docker/Dockerfile
  nautobot/core/settings.py
  nautobot/extras/apps.py
  nautobot/extras/health_checks.py
Labels: emergent
