Repository nautobot/nautobot, pull requests merged in 2025-05, with the labels that each got.

#7212 softwareimagefile ui component
  changes/7212.housekeeping
  nautobot/dcim/tables/devices.py
  nautobot/dcim/tables/devicetypes.py
  nautobot/dcim/templates/dcim/softwareimagefile_retrieve.html
  nautobot/dcim/views.py
  nautobot/virtualization/tables.py
Labels: qa-approved

#7224 Modified filters
  changes/7224.changed
  changes/7224.fixed
  nautobot/cloud/views.py
  nautobot/core/ui/object_detail.py
  nautobot/dcim/views.py
  nautobot/docs/development/apps/migration/ui-component-framework/index.md
  nautobot/extras/filters/__init__.py
  nautobot/extras/views.py
  nautobot/ipam/filters.py
Labels: qa-approved

#7184 Refactored RadioProfileUIViewSet to use UI Components
  changes/7184.fixed
  changes/7184.housekeeping
  nautobot/core/templatetags/helpers.py
  nautobot/core/ui/object_detail.py
  nautobot/wireless/models.py
  nautobot/wireless/templates/wireless/radioprofile_retrieve.html
  nautobot/wireless/views.py
Labels: emergent, qa-approved

#7232 U/pavan circuittypeuiviewset
  changes/7232.added
  nautobot/circuits/forms.py
  nautobot/circuits/tests/test_views.py
  nautobot/circuits/views.py
Labels: qa-approved

#7231 Refactored DeviceFamilyUIViewSet to use UI Components
  changes/7231.housekeeping
  nautobot/dcim/templates/dcim/devicefamily_retrieve.html
  nautobot/dcim/views.py
Labels: qa-approved

#7243 Refactored DeviceTypeUIViewSet
  changes/7243.housekeeping
  nautobot/dcim/templates/dcim/devicetype.html
  nautobot/dcim/templates/dcim/devicetype_edit.html
  nautobot/dcim/templates/dcim/devicetype_retrieve.html
  nautobot/dcim/templates/dcim/devicetype_update.html
  nautobot/dcim/tests/integration/test_fileinputpicker.py
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
Labels: qa-approved

#7318 Fix an AttributeError in RelationshipColumn rendering
  changes/7318.fixed
  nautobot/core/tables.py
Labels: type: bug, emergent

#7237 Refactored DeviceRedundancyGroup views to use UI component
  changes/7237.housekeeping
  nautobot/core/tests/test_ui.py
  nautobot/core/ui/object_detail.py
  nautobot/dcim/templates/dcim/deviceredundancygroup_retrieve.html
  nautobot/dcim/views.py
Labels: qa-approved

#7287 Refactored CircuitTypeUIViewSet to use UI component framework
  changes/7287.housekeeping
  nautobot/circuits/templates/circuits/circuittype.html
  nautobot/circuits/templates/circuits/circuittype_retrieve.html
  nautobot/circuits/views.py
Labels: qa-approved

#7248 Refactored ModuleBayUIViewSet to use UI Components
  changes/7248.housekeeping
  nautobot/dcim/templates/dcim/modulebay_retrieve.html
  nautobot/dcim/views.py
Labels: qa-approved

#7265 Refactored MetadataTypeUIViewSet to use UI Components
  changes/7265.housekeeping
  nautobot/extras/tables.py
  nautobot/extras/templates/extras/metadatatype_retrieve.html
  nautobot/extras/views.py
Labels: qa-approved

#7300 Rackreservation: UI component
  changes/7300.housekeeping
  nautobot/dcim/forms.py
  nautobot/dcim/templates/dcim/inc/rack_elevation.html
  nautobot/dcim/templates/dcim/rack_elevation.html
  nautobot/dcim/templates/dcim/rackreservation_retrieve.html
  nautobot/dcim/views.py
Labels: qa-approved
