Repository nautobot/nautobot, pull requests merged in 2025-06, with the labels that each got.

#7238 Refactored InterfaceRedundancyGroupUIViewSet to use UI Components
  changes/7238.housekeeping
  nautobot/dcim/templates/dcim/interfaceredundancygroup_retrieve.html
  nautobot/dcim/views.py
Labels: qa-approved

#7480 fix: draggable homepage panels on firefox
  changes/7480.fixed
  nautobot/core/templates/home.html
Labels: type: bug, emergent

#7478 Change JobResult list view to not show logs summary by default.
  changes/7178.changed
  nautobot/extras/tables.py
  nautobot/extras/views.py
Labels: emergent

#7346 Refactored LocationUIViewSet
  changes/7346.housekeeping
  nautobot/core/views/renderers.py
  nautobot/dcim/templates/dcim/location.html
  nautobot/dcim/templates/dcim/location_edit.html
  nautobot/dcim/templates/dcim/location_retrieve.html
  nautobot/dcim/templates/dcim/location_update.html
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
Labels: qa-approved
