Repository nautobot/nautobot, pull requests merged in 2025-04, with the labels that each got.

#7099 Remove jquery loading for RTD
  changes/7099.housekeeping
  mkdocs.yml
Labels: type: housekeeping

#7180 Add Redis caches in ValidationRule lookup
  changes/7180.added
  changes/7180.fixed
  changes/7180.housekeeping
  changes/7180.removed
  nautobot/apps/utils.py
  nautobot/core/jobs/__init__.py
  nautobot/data_validation/apps.py
  nautobot/data_validation/custom_validators.py
  nautobot/data_validation/models.py
  nautobot/data_validation/signals.py
  nautobot/data_validation/tests/__init__.py
  nautobot/data_validation/tests/test_api.py
  nautobot/data_validation/tests/test_custom_validators.py
  nautobot/data_validation/tests/test_filters.py
  nautobot/data_validation/tests/test_models.py
  nautobot/data_validation/tests/test_views.py
  nautobot/extras/datasources/git.py
  nautobot/extras/models/datasources.py
  nautobot/extras/plugins/validators.py
  nautobot/extras/signals.py
  nautobot/extras/tests/test_plugins.py
  tasks.py
Labels: emergent

#7148 Refactored RackGroup
  changes/7148.added
  changes/7148.housekeeping
  nautobot/dcim/forms.py
  nautobot/dcim/templates/dcim/rackgroup.html
  nautobot/dcim/tests/test_views.py
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
Labels: emergent

#7187 Add upstream testing for next
  .github/workflows/plugin_upstream_testing_base.yml
  changes/7187.housekeeping
Labels: emergent

#7056 ClusterUIViewset
  changes/7056.housekeeping
  nautobot/core/templates/components/button/default.html
  nautobot/core/templates/components/button/formbutton.html
  nautobot/core/templates/components/panel/body_content_objects_table.html
  nautobot/core/templates/components/panel/footer_content_table.html
  nautobot/core/ui/object_detail.py
  nautobot/virtualization/urls.py
  nautobot/virtualization/views.py
Labels: emergent, qa-approved

#7200 [3.0] Drop support for python 3.9 and add support for python 3.13
  .github/workflows/build_dependency_image.yml
  .github/workflows/ci_integration.yml
  .github/workflows/ci_pullrequest.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  changes/xxxx.dependencies
  examples/example_app/poetry.lock
  examples/example_app/pyproject.toml
  examples/example_app_with_view_override/pyproject.toml
  nautobot/core/views/paginator.py
  nautobot/docs/development/apps/migration/dependency-updates.md
  nautobot/docs/development/core/release-checklist.md
  nautobot/docs/overview/application_stack.md
  nautobot/docs/release-notes/version-3.0.md
  nautobot/docs/user-guide/administration/guides/docker.md
  nautobot/docs/user-guide/administration/installation/index.md
  nautobot/docs/user-guide/administration/upgrading/upgrading.md
  poetry.lock
  pyproject.toml
Labels: emergent

#7156 Fixed multiple invalid default values in the swagger schema
  changes/6157.fixed
  changes/6157.housekeeping
  nautobot/core/api/fields.py
  nautobot/core/api/schema.py
  nautobot/core/tests/test_csv.py
  nautobot/core/tests/test_openapi.py
  poetry.lock
  pyproject.toml
Labels: emergent

#7141 Refactored power panel uiviewset
  changes/7141.housekeeping
  nautobot/core/templatetags/helpers.py
  nautobot/core/ui/object_detail.py
  nautobot/dcim/templates/dcim/powerpanel.html
  nautobot/dcim/templates/dcim/powerpanel_edit.html
  nautobot/dcim/templates/dcim/powerpanel_retrieve.html
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
Labels: emergent, qa-approved

#7160 Refactored ComputedFieldUiViewSet
  changes/7159.added
  changes/7159.housekeeping
  nautobot/extras/forms/forms.py
  nautobot/extras/templates/extras/computedfield.html
  nautobot/extras/templates/extras/computedfield_edit.html
  nautobot/extras/templates/extras/computedfield_retrieve.html
  nautobot/extras/tests/test_views.py
  nautobot/extras/urls.py
  nautobot/extras/views.py
Labels: qa-approved

#7126 Refactored CustomLink
  changes/7126.added
  changes/7126.housekeeping
  nautobot/core/templatetags/helpers.py
  nautobot/extras/forms/forms.py
  nautobot/extras/templates/extras/customlink.html
  nautobot/extras/tests/test_views.py
  nautobot/extras/urls.py
  nautobot/extras/views.py
Labels: emergent, qa-approved

#7155 Refactored RackReservationUIviewset
  changes/7154.housekeeping
  nautobot/dcim/templates/dcim/rackreservation.html
  nautobot/dcim/templates/dcim/rackreservation_edit.html
  nautobot/dcim/templates/dcim/rackreservation_retrieve.html
  nautobot/dcim/urls.py
  nautobot/dcim/views.py
Labels: emergent, qa-approved

#7175 Refactored JobButtonUIViewSet to use UI Components
  changes/7175.housekeeping
  diff
  nautobot/core/templatetags/helpers.py
  nautobot/extras/templates/extras/jobbutton_retrieve.html
  nautobot/extras/views.py
Labels: emergent, qa-approved

#7204 Refactored SoftwareVersionUIViewSet to use UI Components
  changes/7204.housekeeping
  nautobot/dcim/templates/dcim/softwareversion_retrieve.html
  nautobot/dcim/views.py
Labels: qa-review-request
